#!/bin/bash
#
# Copyright (c) 2018 Baozhu Zuo <zuobaozhu@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -x

# OVERLAYS:
OVERLAYS=/boot/dtb/overlay

# Lubancat:
CONFIG=/boot/uEnv/uEnv.txt

is_1a=$(i2cdetect -y  3 0x1a 0x1a | egrep "(1a|UU)" | awk '{print $2}')
is_35=$(i2cdetect -y  3 0x35 0x35 | egrep "(35|UU)" | awk '{print $2}')
is_3b=$(i2cdetect -y  3 0x3b 0x3b | egrep "(3b|UU)" | awk '{print $2}')

overlay=""

if [ "x${is_1a}" != "x" ] && [ "x${is_35}" == "x" ] ; then
    echo "install 2mic"
    overlay=seeed-2mic-voicecard
    asound_conf=/etc/voicecard/asound_2mic.conf
    asound_state=/etc/voicecard/wm8960_asound.state
fi

if [ "x${is_3b}" != "x" ] && [ "x${is_35}" == "x" ] ; then
    echo "install 4mic"
    overlay=seeed-4mic-voicecard
    asound_conf=/etc/voicecard/asound_4mic.conf
    asound_state=/etc/voicecard/ac108_asound.state
fi

if [ "x${is_3b}" != "x" ] && [ "x${is_35}" != "x" ] ; then
    echo "install 6mic"
    overlay=seeed-8mic-voicecard
    asound_conf=/etc/voicecard/asound_6mic.conf
    asound_state=/etc/voicecard/ac108_6mic.state
fi

if [ "$overlay" ]; then
    echo Install $overlay ...

    # Remove old configuration
    rm /etc/asound.conf

    # svae old asound.state
    mv /var/lib/alsa/asound.state /var/lib/alsa/asound_old.state

    kernel_ver=$(uname -r) # get_kernel_version)
    # echo kernel_ver=$kernel_ver

    echo "create $overlay asound configure file"
    ln -s $asound_conf /etc/asound.conf
    echo "$overlay asound status file"
    ln -s $asound_state /var/lib/alsa/asound.state
fi

alsactl restore

#Force 3.5mm ('headphone') jack
#   The Raspberry Pi 4, released on 24th Jun 2019, has two HDMI ports,
#   and can drive two displays with audios for two users simultaneously,
#   in a "multiseat" configuration. The earlier single virtual ALSA
#   option for re-directing audio playback between headphone jack and HDMI
#   via a 'Routing' mixer setting was turned off eventually to allow
#   simultaneous usage of all 3 playback devices.

# if aplay -l | grep -q "bcm2835 ALSA"; then
#     amixer cset numid=3 1 || true
# fi
